version: '3.8'

services:
  nest-app:
    image: node:20-alpine
    container_name: task-management
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: development
    command: yarn start:dev
